### ISSUE TITLE
Add Appveyor build for Windows compatibility testing

### ISSUE THREAD

**Issue by nkbt** [istarkov/babel-plugin-webpack-loaders#10]
Following up #5

**Comment by nkbt** [comment]
I've got configs working fine on my projects so can do this quite quickly

**Comment by istarkov** [comment]
Super, I'll register there in a few minutes, all can broke again because of this https://github.com/istarkov/babel-plugin-webpack-loaders/pull/9 and one other PR

**Comment by istarkov** [comment]
Done,
![image](https://cloud.githubusercontent.com/assets/5077042/12312942/970fbdc6-ba74-11e5-8dff-56d29a3c20d5.png)

Also I've added you to collaborators so you can push any commits.

Do I need to change any settings there?

**Comment by nkbt** [comment]
No changes there, that's ok. Usually I add a checkbox "do not run on branches without appveyour config" or something like that, but it is not a problem anyway.
