### ISSUE TITLE
Quesiton: "ES" build for webpack 2 tree shaking compatibility

### ISSUE THREAD

**Issue by GabeMedrash** [istarkov/babel-plugin-webpack-loaders#101]
If I wanted to create an "ES" build of a library such that `import`/`export` statements are not transpiled (e.g., essentially the es2015 babel present without "transform-es2015-modules-commonjs"), is it still possible to use this plugin? I would want to do so in order to take advantage of new [tree shaking](http://www.2ality.com/2015/12/webpack-tree-shaking.html) functionality in webpack 2.

**Comment by istarkov** [comment]
`import/export` of what?

**Comment by GabeMedrash** [comment]
Well, maybe I should have led with an example:
Given `foo.js`
```
import styles from './style.css'

return styles.title;
```

And `style.css`
```
.title {
  font-weight: bold;
}
```

My understanding is that in a typical (that is, babel/webpack 1.x setup), `foo.js` is transpiled into
```
var styles = require('./style.css');
return styles.title;
```
***before*** this loader is able to operate. Right?

My goal is to _not_ have to transpile `import` statements, which would therefore include `import styles from './style.css'`. 

I suppose though that another babel plugin could be written that **only** transpiles `imports` of css files...

**Comment by istarkov** [comment]
Sorry I can't get the question at all.

**Comment by GabeMedrash** [comment]
Shoot, sorry, I'm not being very clear. One more try: 
Is this plugin able to operate on the statement `import style from './style.css'`? Or can it only operate on the statement, `var style = __webpack_require__(...);`

**Comment by istarkov** [comment]
Yes it works well with `imports`

**Comment by istarkov** [comment]
First examples in documentation all use imports https://github.com/istarkov/babel-plugin-webpack-loaders/blob/master/examples/myCoolLibrary/myCoolLibrary.js etc

**Comment by GabeMedrash** [comment]
Yes but in your `.babelrc` you use babel-present-es2015 (which transpiles `import`/`export` statements). I believe it would not work if you were to use babel-preset-es2015-webpack (which is babel-preset-es2015 without the module transform) instead. I've been trying to test this but have been having difficulty building locally.

**Comment by istarkov** [comment]
Without preset it will not work, as I intercept require ast

**Comment by GabeMedrash** [comment]
Ok gotcha, thank you, that's what I was wondering. Is there any way to intercept an import in addition?

**Comment by istarkov** [comment]
Not a big problem to transform ast one level up, I will accept a PR with such extension, BTW I will not implement it by myself. As almost have no time now.

**Comment by GabeMedrash** [comment]
Sounds great, thanks. I'd be happy to take a shot at it--don't have much capacity at the moment either, but I may find some time soon.

**Comment by todd-richmond** [comment]
@GabeMedrash did you find a solution for tree shaking eliminating your CSS? I have the same problem and am not sure how to work around it. If you use 2015-webpack, my CSS is optimized out and so never built by webpack

**Comment by GabeMedrash** [comment]
@todd-richmond Unfortunately no--haven't been able to find the time. Still hoping to at some point, but hard for me to predict when things will slow down enough for that to happen. If you stumble on a solution would love to hear it.
