### ISSUE TITLE
Missing documentation or context about being usable for backend purposes only

### ISSUE THREAD

**Issue by vvo** [istarkov/babel-plugin-webpack-loaders#104]
Hi, I am trying to use this plugin as a way to resolve webpack loaders on a per file basis so that I can inline some stylesheets in my library when loaded via commonjs.

I have an ES6 frontend library https://github.com/algolia/places that I want people to be able to require() via browserify/webpack. I have some SVG icons and CSS files, SVG raw-loader works perfectly but just trying to use style-loader and css-loader fails. I just want the main JavaScript file to inline the style-loader code.

The output is empty as soon as I try to use style-loader and css-loader.

Here's an example project: https://github.com/vvo/babel-plugin-webpack-loaders-test

Reading the readme I can see that this library is mainly for BACKEND purposes but I am failing at understanding why exactly?

Do you think I can achieve somehow what I am looking for? Maybe I should split the css-loader from the style-loader usage and insert the CSS myself after getting its content in a variable? Thanks.

**Comment by istarkov** [comment]
There are a lot of examples in this library tests and docs, please check them an compare with your setup.

**Comment by istarkov** [comment]
Just reread, for inlining frontend code, you could just use webpack itself. There is no need in this library.

**Comment by vvo** [comment]
> Just reread, for inlining frontend code, you could just use webpack itself. There is no need in this library.

I found a workaround. All I need is to be able to get the sass and css loader to inline the content into the file passed.

Using your example here: https://github.com/istarkov/minimal-example-for-babel-plugin-webpack-loaders and modifying the webpack config to this:

```js
// webpack.config.js css-modules loader example
module.exports = {
  output: {
    // YOU NEED TO SET libraryTarget: 'commonjs2'
    libraryTarget: 'commonjs2',
  },
  module: {
    loaders: [
      {
        test: /\.css$/,
        loaders: [
          'style-loader',
          'css-loader'
        ],
      },
    ],
  },
};
```

I get `undefined` in the console.log(css); Am I missing something?

**Comment by istarkov** [comment]
You will get the same with `webpack` as css-loader with style-loader does not return any result in require.

**Comment by istarkov** [comment]
just css-loader with css-modules 'css-loader?modules...' will give you some output

**Comment by vvo** [comment]
Just tried with "css-loader" alone and go nothing, yet it works with css-loader?modules but I do not use css-modules. Is there a bug or am I clearly not understanding the scope of your module?

Thanks

**Comment by istarkov** [comment]
Please read the css-loader documentation. It should not return anything.

**Comment by vvo** [comment]
I just read it and tested it, using css-loader with webpack alone does inline the CSS content inside the variable. But using it with babel-plugin-webpack-loaders will not output anything

**Comment by vvo** [comment]
```js
var css = require("css!./file.css");
// => returns css code from file.css, resolves imports and url(...)
```

from https://github.com/webpack/css-loader#usage

**Comment by vvo** [comment]
I can fix the issue on my side by using: ['raw', 'css', 'sass'] loaders but I am not sure we are doing everything the right way here.

**Comment by vvo** [comment]
Let me know if you want to debug this further or just want to close it as being irrelevant.

**Comment by istarkov** [comment]
As I see in real webpack app `css = require("css!./file.css")` returns an array,like 
```
0: 824
1 : "body, html {↵  font-size: 16px!important;↵}↵.spectacle-content {↵  max-width: 1200px!important;↵}↵"
2: ""
```
In real life I have no idea for what I could use this array, (All my life I thought that css-loader itself return nothing ;-)) so Yes it looks like a bug, but I will not investigate why until some more real bug appears. 

So let's stay it open for now. 
Thank you!

**Comment by vvo** [comment]
I feel I would need to use https://github.com/gajus/to-string-loader but I am unable to make it work properly :)

**Comment by vvo** [comment]
Ok made it work, thanks a lot.

As for reference to anyone coming here, you can inline css-loader output by using: ['to-string', 'css', 'sass'] loaders.
