### ISSUE TITLE
"Cannot find module" on Windows 10 

### ISSUE THREAD

**Issue by SOSANA** [istarkov/babel-plugin-webpack-loaders#106]
@istarkov 

Currently using your plugin on with [mern-starter](https://github.com/Hashnode/mern-starter) but an issue with various users using windows had the error "Cannot find module". Details for the problem and quick fix are detailed [here](https://github.com/Hashnode/mern-starter/issues/170) as it turns out these where the directions to fix the problem

Open ```~\node_modules\babel-plugin-webpack-loaders\lib\runWebPackSync.js```

Go to line 41, replace

```
var webPackStdOut = (0, _child_process.execSync)((0, _shellQuote.quote)(['node', webPackPath, path, outPath, '--config', configPath, '--bail']));
```
with

```
var webPackStdOut = (0, _child_process.execSync)(['node', webPackPath, path, outPath, '--config', configPath, '--bail'].join(' '));
```

Should we create a pr with this adjustment or did you want to look into this and give thoughts?

**Comment by istarkov** [comment]
I think if your PR will not break the tests I will accept it. 
Even it cause some bad things, we could just check the OS platform and provide a different results for windows and other envs.

**Comment by SOSANA** [comment]
cool! @istarkov I will test right now

**Comment by SOSANA** [comment]
PR #107 ready for review, passing tests

**Comment by SOSANA** [comment]
@istarkov  PR #107 ready for review, passing tests

**Comment by SOSANA** [comment]
closing as per PR #107

**Comment by SOSANA** [comment]
closing as per PR #107
