### ISSUE TITLE
Infinite loop with json-loader

### ISSUE THREAD

**Issue by MoOx** [istarkov/babel-plugin-webpack-loaders#14]
Hi,

First of all, thanks for this project. I was thinking about it everyday for some weeks and before starting working on it, I found this one.

I am currently trying it on a project that where using webpack to build a node script (which is kind of annoying). I am facing an issue.

My configuration is having a section for json on client side

```
    {
        test: /\.json$/,
        loader: "json-loader",
      },
```

This part create (not sure why) an infinite process, stuck where the required json is called.
Removing it fixed the thing.
I can add this to my config only when used for client. That's a solution.

But at the same time, I am wondering if some loader should not be blacklisted.
Like babel-loader. For client build, babel-loader might make sense. But in the context of this project, (which is "run your code via babel), babel-loader doesn't make any sense, like json-loader. Maybe we should blacklist those?

**Comment by MoOx** [comment]
That might be related to the fact that I didn't used `libraryTarget: "commonjs2"`.

**Comment by istarkov** [comment]
Here is fast example how I use server config and client https://github.com/istarkov/babel-plugin-webpack-loaders/blob/master/examples_webpack_configs/client.webpack.config.js

I just take loaders from server (lib) config, and add (override) other settings. May be this help. I'll take a look at json loader later.

**Comment by MoOx** [comment]
Thanks, I have seen this example.
Now I am facing a weird issue when using "react-svg-loader", which create me this

```
/Users/MoOx/Sync/Development/statinamic/docs/web_modules/Header/index.js:27
var _statinamicText = deprecated;
                      ^

ReferenceError: deprecated is not defined
```

My original line is `import StatinamicLogoSVG from "../../../logo/statinamic-text.svg"` and my config is pretty simple for svg

```
      {
        test: /\.svg$/,
        loaders: [
          "react-svg-loader",
        ],
      },
```

So not sure why I am getting this weird output :D

**Comment by MoOx** [comment]
For the json-loader thing when using `libraryTarget: "commonjs2".` is does not create a loop so I guess I can close this issue?
If you have any clue for the svg thing... :)

**Comment by istarkov** [comment]
I have never used react-svg-loader before, will look
