### ISSUE TITLE
Cannot specify NODE_PATH

### ISSUE THREAD

**Issue by tquetano-r7** [istarkov/babel-plugin-webpack-loaders#145]
When running AVA, we need to specify NODE_PATH due to the fact that we leverage the resolve fallback option of specifying a primary "root" folder for imports. It works just fine with AVA by itself, but it does not appear to be respected when this plugin is applied. Is it possible that this support could be added? 

I'm not sure why its swallowing it up (maybe running things on a child process and not passing them through?) but it would be awesome if it could either be respected as-is:

```
NODE_PATH=./src NODE_ENV=test ava --verbose --no-cache
```

or as a configuration option:

```
{
  "env": {
    "test": {
      "plugins": [
        ["babel-plugin-webpack-loaders", {
          "config": "${CONFIG}",
          "resolvePath": "./src",
          "verbose": true
        }]
      ]
    }
  },
  "plugins": [...]
}

```

Thanks!

**Comment by istarkov** [comment]
Isn't NODE_PATH is just the same as webpack modulesDirectories in resolve?

https://github.com/istarkov/babel-plugin-webpack-loaders/blob/ae2b860eaab5c2d937d77868a2ec6cf0461753c3/test/runtime.webpack.config.js#L22-L26

**Comment by tquetano-r7** [comment]
Should be just the same, but I didn't see anything in your documentation about being able to use moduleDirectories with this either. I experimented with using resolve: fallback like we do in webpack and it was not respected, so I assumed that loaders were the only piece that way. If there is a way to leverage `moduleDirectories` I'll give it a go.
