### ISSUE TITLE
can't install the plugin with webpack 2

### ISSUE THREAD

**Issue by ashraffayad** [istarkov/babel-plugin-webpack-loaders#150]
I'm using webpack 2.1.0-beta.22.
I keep receiving this error:

babel-plugin-webpack-loaders@0.7.1 requires a peer of webpack@>=1.12.9 <3.0.0 but none was installed.

Thanks.

**Comment by istarkov** [comment]
I will accept a PR with fix.

**Comment by ctrlplusb** [comment]
@ashraffayad it's just a warning.  I am using the latest 2.1.0-beta.25 and it is working fine. :)

**Comment by loklaan** [comment]
Closing, as this is to do with NPM not this plugin. (Good to hear it stopped warnings with a higher version)
