### ISSUE TITLE
Supporting additional webpack module api's

### ISSUE THREAD

**Issue by loklaan** [istarkov/babel-plugin-webpack-loaders#163]
Hi there! Cool plugin!

I'd like to get some feedback on a proposal.

Most of the [advanced](https://webpack.github.io/docs/api-in-modules.html#advanced) webpack module API's haven't been implemented in the plugin, like (but not limited to):

```
__webpack_require__
__webpack_public_path__
__webpack_modules__
__webpack_chunk_load__
__non_webpack_require__
```

I _think_ this might break several webpack loaders out in the wild.

Adding support for some or all of these API's would be awesome. ✨ 

The [spec](https://webpack.github.io/docs/api-in-modules.html#advanced) and [implementation in webpack](https://github.com/webpack/webpack/blob/master/lib/APIPlugin.js#L13) can serve as a reference. The transforms would need to happen in AST though. I am not sure all API's can be implemented, but the simpler ones like `__non_webpack_require__` could.

I think this might be a good issue for others/myself to take on during [Hacktober Fest](https://hacktoberfest.digitalocean.com/), so adding that label would be cool to get people interested.

Let me know what you think of the proposal. 😊

**Comment by istarkov** [comment]
You are collaborator now :-) Do anything u like

**Comment by loklaan** [comment]
Nice one mate, cheers.

**Comment by loklaan** [comment]
I'll leave this around for a couple days to see if anyone is keen to open a PR, then I'll jump on it for a few of the API's.
