### ISSUE TITLE
Can't resolve jsx files on despite of loader is present

### ISSUE THREAD

**Issue by creaux** [istarkov/babel-plugin-webpack-loaders#165]
I'm very curios about following error. 

```
Error: /Users/xxx/Development/javascript/redux/project/src/entry-server.js: Can't resolve './hoc/storeProvider' in '/Users/xxx/Development/javascript/redux/project/src'
```

I'm using reactjs so using jsx files thats why I added following loader.

``` javascript
      ...
      {
        test: /\.jsx?$/,
        loaders: ['babel?cacheDirectory'],
      },
      ...
```

I realized that you maybe not support `babel-loader` but on the other hand it looks to me like one the most mandatory. Can you give me some hint about that?

**Comment by loklaan** [comment]
Hey mate.

I'd like to help you, but I need more information.

* Same error, but with a stack message
* What are you trying to do?

**Comment by istarkov** [comment]
As it is a plugin for babel it means that babel is already has run when this plugin start to work, so it can't support babel loaders.
It means that you should set your babel configuration at `.babelrc` or in `package.json`.

Also this plugin intended to replace `require|import` with webpack loader output, it's easy when output of loader is resource like string, json, but this will not work if output is executable code.

By the reason above this plugin will not support babel-loader.

**Comment by adam1658** [comment]
Does adding
```
  resolve: {
    extensions: ['', '.js', '.jsx'],
  },
```
to your webpack config help?

**Comment by creaux** [comment]
Yes wrong config as @adam1658 proposed.
