### ISSUE TITLE
Alternative way to specify the babel env

### ISSUE THREAD

**Issue by MoOx** [istarkov/babel-plugin-webpack-loaders#17]
The current method is not really "cross platform" in the way you need a different command on windows to set an env variable.
Do you think we could found another (more cross platform) way to setup the babel env? Maybe using babel-register with option?

**Comment by istarkov** [comment]
Isn't NPM on windows automatically add `cross-env` to vars inside package.json script tag

**Comment by istarkov** [comment]
Also I moved a lot of my friends from windows to linux and osx. 
May be having a bit of pain everyday all other windows developers will move too.

**Comment by MoOx** [comment]
npm does not handle cross-env by default.
I understand your point but I still think it should be nice to have another solution.

**Comment by MoOx** [comment]
not urgent tho.

**Comment by istarkov** [comment]
Alternative way :-)
https://github.com/istarkov/babel-plugin-webpack-loaders/blob/master/test/warning.warn.js#L25-L43

**Comment by MoOx** [comment]
So if I use [babel-register](https://babeljs.io/docs/usage/require/) with the appropriate config, and then ``require`` my code it should work?

**Comment by istarkov** [comment]
Yes, If babel register has the same arguments as transform

**Comment by MoOx** [comment]
So it's kind of obvious when you think about it.

**Comment by istarkov** [comment]
?

**Comment by MoOx** [comment]
I mean it's easy to use your plugin. It's a babel plugin, so you can just use it as any other plugins.
ENV or register.
You cannot really offer alternative way to run it. It's "just some babel config" after all.
I don't really know if this issue is relevant.
