### ISSUE TITLE
NPM doesn't have correct github repo or latest release

### ISSUE THREAD

**Issue by rcline** [istarkov/babel-plugin-webpack-loaders#174]
Hey!

I am looking into using this to solve some Universal asset issues I am running across.  We are currently using babel server side and webpack client side, so this seems perfect.

I assume this is the correct NPM package? https://www.npmjs.com/package/webpack-for-babel-plugin

It is currently pointed at Dan Abramov's `react-transform-boilerplate` with a latest release of `0.0.3`.

It looks like there isn't any git tags on `babel-plugin-webpack-loaders` releases as well.

The specific issue I run across is not being able to install the latest release:
```
$ npm i webpack-for-babel-plugin
webpack-for-babel-plugin@0.0.3 node_modules/webpack-for-babel-plugin
```

Let me know if you need any help with this.

Thanks!
Ryan

**Comment by istarkov** [comment]
I have no idea what the reference you gave above and why ;-)

Here is the npm package:
https://www.npmjs.com/package/babel-plugin-webpack-loaders

It easy to get the npm package name just from `npm install` command from readme, or from this line of package.json https://github.com/istarkov/babel-plugin-webpack-loaders/blob/master/package.json#L2

**Comment by rcline** [comment]
Oh wow! So sorry.

Yup that npm package link looks much better.  However the link I gave is also under your name, published 10 months ago, and has a very similar readme.  Should probably kill it to avoid confusion as it was the first result in my google search :(

Thanks, and thank you for this plugin!!!

**Comment by istarkov** [comment]
Thank you,
I'll try to find the way on npm to view all my packages and to remove unused.

Yes looks like it was my fault publish ;-)
