### ISSUE TITLE
[Windows] Can't resolve '../../../file.css'

### ISSUE THREAD

**Issue by jhen0409** [istarkov/babel-plugin-webpack-loaders#21]
https://ci.appveyor.com/project/jhen0409/react-chrome-extension-boilerplate/build/1.0.70#L51

[My project](https://github.com/jhen0409/react-chrome-extension-boilerplate) is used babel-plugin-webpack-loaders now, but it's an error on AppVeyor.

Also, it's work well on [Travis](https://travis-ci.org/jhen0409/react-chrome-extension-boilerplate).

**Comment by istarkov** [comment]
I've just created #22 PR with require via `..` path, all works fine at appveyor. 
Could you create a failing test example PR?

I have not windows at all, so I can't help you as in Linux env all works fine.

**Comment by istarkov** [comment]
Also please check last npm version 0.3.0
Resolve has some changes.

**Comment by jhen0409** [comment]
@istarkov thanks! It work with v0.3.0.

But it appears a new problem, I cannot require node native api:
```
Can't resolve 'fs' in '/Users/Jhen/github/react-chrome-extension-boilerplate/test/e2e/injectpage.js'
```

**Comment by istarkov** [comment]
And what I must do? There are options to fake native node api via webpack, but do I need to resolve this issues?

**Comment by istarkov** [comment]
But looks like I get this problem, give me a time to resolve ;-)

**Comment by istarkov** [comment]
https://github.com/istarkov/babel-plugin-webpack-loaders/pull/25

**Comment by jhen0409** [comment]
Thanks a lot! It resolved. :)
