### ISSUE TITLE
Fails with jsdom

### ISSUE THREAD

**Issue by karlhorky** [istarkov/babel-plugin-webpack-loaders#26]
I've been trying to include `jsdom` in my tests, and it is failing on trying to resolve the `fs` module used within `jsdom`.

*component.test.js*
```js
const jsdom = require('jsdom');

// OR

import jsdom from 'jsdom';
```

*Error*
```bash
ModuleNotFoundError: Module not found: Error: Cannot resolve module 'fs' in /Users/karlhorky/projects/k/node_modules/jsdom/lib
```

*webpack config*
```js
const path = require('path');

module.exports = {
  module: {
    loaders: []
  },
  resolve: {
    modules: [
      __dirname,
      path.resolve(__dirname, 'node_modules')
    ]
  },
  output: {
    libraryTarget: 'commonjs2'
  }
};
```

**Comment by karlhorky** [comment]
Ah, if I guess this is a problem with calling the babel loader also in the webpack config. If I remove that it seems to work:

```diff
const path = require('path');

module.exports = {
  module: {
-    loaders: [{
-      test: /\.js$/,
-      exclude: /node_modules|bower_components/,
-      loader: 'babel'
-    }]
+    loaders: []
  },
  resolve: {
    modules: [
      __dirname,
      path.resolve(__dirname, 'node_modules')
    ]
  },
  output: {
    libraryTarget: 'commonjs2'
  }
};
```

**Comment by karlhorky** [comment]
It seems to have been caused by 44111048cafeca5887acbd6693f3f91c5f99df78. Maybe moving the `.resolveSync()` outside of the `if (config.module.loaders.some ... )`?

**Comment by karlhorky** [comment]
Yeah, seems to work in my case if I move the `resolve` back into the if statement.

@istarkov You probably moved them out for a reason, any tips as to what I should do here?

```diff
        const config = localInteropRequire(resolve(process.cwd(), configPath));
        if (Object.keys(config).length === 0) {
          // it's possible require calls inside webpack config or bad config
          return;
        }

+       if (config.module.loaders.some((l) => l.test.test(filePath) || l.test.test(fileAbsPath))) {
        const [{ value: filePath }] = args;

        // to support babel builds (babel-node works fine)
        const filenameAbs = resolve(filenameRelative);

        const resolver = getEnhancedResolver(config);

        const fileAbsPath = resolveFilePath(resolver, filenameAbs, filePath);
        // resolver.resolveSync({}, dirname(filenameAbs), filePath);

        if (!fileAbsPath) {
          return;
        }

-       if (config.module.loaders.some((l) => l.test.test(filePath) || l.test.test(fileAbsPath))) {
          const webPackResult = runWebPackSync({ path: fileAbsPath, configPath, config, verbose });
```

**Comment by istarkov** [comment]
Yes was the reason, look into the latest test.
But I check on fs inside plugin, mb the problems with babel cache?
https://github.com/istarkov/babel-plugin-webpack-loaders/blob/master/src/plugin.js#L119

**Comment by karlhorky** [comment]
Hm, I'm running it without the cache:

```bash
$ BABEL_DISABLE_CACHE=1 BABEL_ENV=test mocha --compilers js:babel-register --require ignore-styles public/src/components/**/*.test.js
```

**Comment by karlhorky** [comment]
I'll try writing a failing test case.

**Comment by istarkov** [comment]
https://github.com/istarkov/babel-plugin-webpack-loaders/blob/master/test/runtime.spec.js#L58

**Comment by karlhorky** [comment]
I've created a failing example here: https://github.com/istarkov/minimal-example-for-babel-plugin-webpack-loaders/pull/3

**Comment by istarkov** [comment]
#27

**Comment by istarkov** [comment]
Done, please read https://github.com/istarkov/babel-plugin-webpack-loaders/pull/27#issuecomment-184368531

**Comment by istarkov** [comment]
in v 0.3.3

**Comment by karlhorky** [comment]
`0.3.4` looks good. Still getting some small issues, but they are not jsdom related. Closing, thanks for this!
