### ISSUE TITLE
Ignore files which is not in loaders

### ISSUE THREAD

**Issue by morlay** [istarkov/babel-plugin-webpack-loaders#33]
`babel-plugin-webpack-loaders` is cool.

In v0.3,  `babel-plugin-webpack-loaders` will parse the file which is not in `loaders`.
![image](https://cloud.githubusercontent.com/assets/1667873/13132925/f603a396-d631-11e5-9a5c-2ecb94f64312.png)
Not sure this is necessary.

In v0.2,  there is no the behavior.

It is looks because of the  `enhanced-resolve@2`

**Comment by istarkov** [comment]
Thank you, will check today.

**Comment by istarkov** [comment]
It's is an expected error, it shows that you import file which can't be processed. 
What the need of `import xxx from 'blbla.eee'` if `blbla.eee` has unexpected file format.

So I think it works as like I want.

**Comment by morlay** [comment]
But it will try to resolve Javascript file too. 
This may not an expected behavior.

**Comment by istarkov** [comment]
Please provide error example with javascript file. Even you change js-jsx extension on other (why?) I think you can add this extension to resolve extensions config, and all will be fine.

**Comment by morlay** [comment]
Some times, we will put code like below

```
modules/
   some-module/
     index.js
app/
  index.css
  index.js
```
in `app/index.js`, we put code `import some from 'modules/some-module';`
it will should error "not find module 'modules/some-module'  ..."
I know i can config the `resolve.modulesDirectories' to make it work. 

But I think as a `babel-plugin`, we don't need to resolve that file ('modules/some-module') in babel transformation.

**Comment by istarkov** [comment]
We need to resolve every such situation, 

1) It is some kind of static checking that code can be runned.

2) In your example if you `require(DIRECTORY)`, default file in directory can be not a js file 
(_for example you have there package.json file)

And as in require docs

```
LOAD_AS_DIRECTORY(X)
1. If X/package.json is a file,
   a. Parse X/package.json, and look for "main" field
```

`main` can be reference to a file which this plugin must! process.

So I can't get your arguments.

**Comment by morlay** [comment]
It is not my point, even i use `modules/some-module/index`, it will show the same error.
I means, Should we need to resolve every dependences of the target file in a `babel-plugin` ?

**Comment by istarkov** [comment]
> Should we need to resolve every dependences of the target file in a babel-plugin

Yes, because I promise that every dependency which pass loader test will be converted, without resolving dependency I can't do it. 

If I can't resolve dependency it is an error.

It is the same as webpack work.

Without a real! problem there is no need in this discussion. 

All I see from above is examples their will never can be executed so there is no need to compile them.

If you have a real problem please describe it here.

**Comment by morlay** [comment]
Sure, Thanks.
