### ISSUE TITLE
Pick wrong ast node when results with dependences 

### ISSUE THREAD

**Issue by morlay** [istarkov/babel-plugin-webpack-loaders#34]
It is be mentioned in https://github.com/istarkov/babel-plugin-webpack-loaders/issues/14
```js
/Users/MoOx/Sync/Development/statinamic/docs/web_modules/Header/index.js:27
var _statinamicText = deprecated;
                      ^
ReferenceError: deprecated is not defined
```

For now, the tested loaders in example, `css-loader`, `file-loader`,  `png-loader`, will return a simple module.
```js
modules.exports  = webpackBootstrap([
/* 0 */
/***/ function(module, exports, __webpack_require__) {
        module.exports = __webpack_require__.p +"fc2bafa27d25941c90e00aadcfd76661.svg";
/***/ }
/******/ ])
``` 
So they will work well.

But in some loader will transform code with other modules. it will be broken, like `react-svg-loader` and mine https://github.com/morlay/svg2jsx

the result will be 
```js
modules.exports  = webpackBootstrap([
/* 0 */
/***/ function(module, exports, __webpack_require__) {
        var  React =  __webpack_require__(1);
        module.exports = React.createElement('div');
/***/ }，
/* 1 */
/***/ function(module, exports, __webpack_require__) {
         
/***/ }
/**and others */
/******/ ])
```
Then `babel-plugin-webpack-loaders` will pick the last one (re-assign until the last, 
https://github.com/istarkov/babel-plugin-webpack-loaders/blob/master/src/plugin.js#L37), 
This is why there is a `deprecated` in the issue at the beginning.

And by the way, should we need to package all dependences ?

**Comment by istarkov** [comment]
For now I have no idea how to support `code generating` loaders, because I don't use any in my production. Also I have no Idea what to do with dependencies in such generated code. For example in your example above - `React` is what? Some strange `__webpack_require__(1)`.

For me loaders is something that just support `resources` (as in some languages), where `resources` is just the data not code.

Also the question is - in what situation I need `svg -> jsx` loader as I can use svg directly in css?

**Comment by morlay** [comment]
The `React` is show that, if the loader return some code have dependences, will have the same issue. 
The `expr` will be assigned more that one time https://github.com/istarkov/babel-plugin-webpack-loaders/blob/master/src/plugin.js#L37.

svg -> jsx is from http://dmfrancisco.github.io/react-icons/ and could be helpful to use inline-svg or to compose svg shapes in javascript.

**Comment by istarkov** [comment]
So if break code execution the result will be as you wish? I'll accept such PR with additional tests for your situation.

**Comment by morlay** [comment]
It will be a trick way, and if run webpack in each file, it will be very. slow..
And I just find a lib under webpack team, https://github.com/webpack/loader-runner

it works 
```js
const path = require('path');
const runLoaders = require('loader-runner').runLoaders;

runLoaders({
  resource: path.join(__dirname, './index.css'),
  loaders: [
    `${require.resolve('css-loader')}?modules&localIdentName=[path][name]---[local]---[hash:base64:5]`
  ],
  context: {
    // maybe use webpack config to replace the context
    minimize: true,
    options: {}
  }
}, function (err, result) {
  console.log(result.result) 
});
```
```css
.root {
    color: red;
}
```
result will return
```
exports = module.exports = require("./../node_modules/css-loader/lib/css-base.js")();
exports.push([module.id, ".index---root---1g6PR{color:red}", ""]);
exports.locals = {
  "root": "index---root---1g6PR"
};
```
Maybe we could using this way instead of running `webpack` directly.
Need to research deeply.

**Comment by istarkov** [comment]
The problem is that we can't use asynchronous functions for this tasks, 
so I use dirty hack to run asynchronous webpack synchronously https://github.com/istarkov/babel-plugin-webpack-loaders/blob/master/src/runWebPackSync.js#L18

(Without need of sync execution I can just use webpack api directly)

As I know there are no other simple way to make async task sync.
There are ways to do this with https://github.com/laverdet/node-fibers but this is really hacky lib, so I dislike to use it.

**Comment by morlay** [comment]
`Fiber` need a wrapper for sync. may have to use https://github.com/abbr/deasync.

```js
import path from 'path';
import webpack from 'webpack';
import deasync from 'deasync';

const runWebpackSync = (filename, webpackConfig) => {
  let result;

  webpack({
    ...webpackConfig,
    entry: filename,
    output: {
      ...options.output,
      // write to a temp folder
      path: path.join(__dirname, '../temp')
    },
    externals: [
      // Ingore all files but the target file
      (context, subRequest, callback) => {
        if (subRequest !== filename) {
          callback(null, '');
        } else {
          callback();
        }
      }
    ]
  }, (err, stats) => {
    if (err) {
      throw err;
    }
   // Only need the the origin source
    result = stats.compilation.modules[0]._source.source()
  });

  // block until result
  deasync.loopWhile(() => result === undefined);

  return result;
};

export default runWebpackSync
```

**Comment by istarkov** [comment]
As I wrote in prev message I dislike the idea of using Fiber lib. Any v8 change can kill this lib. Also I think that soon we get node with other js engines than v8, so Fibers is not a variant for me.

**Comment by morlay** [comment]
Yep, but for now it works. We could fix it until broken.

So I recreate another one, https://github.com/morlay/babel-plugin-webpack-loaders-inline-exports.

Just echo the whole exports code by loader.
