### ISSUE TITLE
CSS Loaders - compile to the directory being loaded from?

### ISSUE THREAD

**Issue by jacktuck** [istarkov/babel-plugin-webpack-loaders#35]
### My application structure is as follows

```
├── js
│   ├── App.js
│   ├── Routes.js
│   ├── components
│   │   └── Header
│   │       ├── Header.js
│   │       └── Header.scss
```

I have tried all the examples, but neither get me quite to where i want to be.

This example got me the closest (`using a .css file`)
https://github.com/istarkov/babel-plugin-webpack-loaders/blob/master/examples_webpack_configs/run.webpack.config.js

### Can the styles be returned in-place (in a style elem) and not output to a file?
So with the above example, the console.log of the css file returned the class names, but i could not find the styles themselves. I basically want it so that when I `require('./Header.css')` or `require('./Header.scss')` (_in Header.js_) I can use the class names and the styles will be included on the page in a `<style>` tag. 

Is that possible with this plugin?

Thanks a lot!

**Comment by istarkov** [comment]
Why not to just use webpack itself. It will add styles on the page. This is a babel plugin intended to work on server env, there is no style tag in javascript.
