### ISSUE TITLE
webpack 3?

### ISSUE THREAD

**Issue by viict** [istarkov/babel-plugin-webpack-loaders#361]
Is there some kind of roadmap to add support for webpack3?

**Comment by istarkov** [comment]
Im not using this plugin anymore, new tech stack like css in js, made this useless for me

**Comment by viict** [comment]
@istarkov I use it just for that, how can achieve that?

**Comment by istarkov** [comment]
that?

**Comment by viict** [comment]
Nevermind haha Just got the way.. thanks anyways
