### ISSUE TITLE
Any way to skip outputPath/main.*.css ?

### ISSUE THREAD

**Issue by MoOx** [istarkov/babel-plugin-webpack-loaders#48]
I guess under the hood it's a normal behavior to get lot's of css files when you use css modules. That said, in my case (universal code), I have a builded css file for client side, so I do not need all those files in my build folder. Any idea how I can safely remove or even better, skip them when using your babel plugin?

**Comment by istarkov** [comment]
As I know css files not created without ExtractText plugin

**Comment by MoOx** [comment]
Yeah but I am using it for my client side bundle. Ok so I should remove part of my config that is handling the extract. Will try that.

**Comment by istarkov** [comment]
The simple way `rm ./build/*.css` as a poststep

**Comment by MoOx** [comment]
No since I still need one css file :)
Trying something better, will share my result.

**Comment by istarkov** [comment]
Better ;-)
`find . -name '*css' | grep -v styleYouNeed.css | xargs rm`

**Comment by MoOx** [comment]
So using the `disable` option of `ExtractTextPlugin` is enough.
I have something like this

```js
  plugins: [
    new ExtractTextPlugin("[name].[hash].css", {
      disable: config.dev ||  process.env.BABEL_ENV === "statinamic",
    }),
```

My BABEL_ENV=statinamic when using your plugin. This seems to avoid the files, as expected.
