### ISSUE TITLE
Webpack 2.x compatibility

### ISSUE THREAD

**Issue by GabeMedrash** [istarkov/babel-plugin-webpack-loaders#54]
So far as I can tell, in Webpack 2.x, `--colors` is no longer a valid CLI option. `--color` is now the supported option. Running this plugin using Webpack 2.1.0-beta.4 (current as of today) produces a huge console error, though the meat of it is: `Unknown argument: colors`. 

Changing the option to `--color` in `lib/runWebPackSync.js` fixes the issue, though I'm assuming would break compatibility with Webpack 1.x.

**Comment by istarkov** [comment]
Looks like removing colors options will not break anything. You could provide a PR, and I feel all tests will be completed. So if no issues will be in tests I'll accept your PR.

**Comment by GabeMedrash** [comment]
Thanks, @istarkov. Just submitted the suggested [PR](https://github.com/istarkov/babel-plugin-webpack-loaders/pull/55).

**Comment by istarkov** [comment]
Thank you!!!! Published as 0.3.10

**Comment by GabeMedrash** [comment]
You're awesome--thanks so much for the quick response and merge!
