### ISSUE TITLE
Is there a way to combine all styles into one file?

### ISSUE THREAD

**Issue by nikgraf** [istarkov/babel-plugin-webpack-loaders#61]
With ExtractTextPlugin and the option allChunks you usually can extract all styles into one file. I couldn't manage to get this working. Usually `{ allChunks: true }` does the trick.

**Comment by istarkov** [comment]
Copy of
https://github.com/istarkov/babel-plugin-webpack-loaders/issues/43

The problem that I can't use single webpack instance, so the recommended way is to use something like 
`cat *.css > combined.css`

**Comment by istarkov** [comment]
Example https://github.com/istarkov/react-components-markdown/blob/master/package.json#L9

**Comment by nikgraf** [comment]
thx, makes sense to me now :)
