### ISSUE TITLE
Cannot read property 'some' of undefined

### ISSUE THREAD

**Issue by giacomorebonato** [istarkov/babel-plugin-webpack-loaders#69]
I am trying to running test on a ReactJS codebase with CSS modules.
When I run the test with Ava, I receive the following message  

```
TypeError: /client/setup.js: Cannot read property 'some' of undefined
    at PluginPass.CallExpression (/node_modules/babel-plugin-webpack-loaders/lib/plugin.js:81:34)
```

setup.js contains the initialization of jsdom  
```js
import jsdom from 'jsdom'

global.document = jsdom.jsdom('<html><body></body></html>')
global.window = document.defaultView
global.navigator = window.navigator
```

Could you point me in the right direction for the solution?
Cheers.

**Comment by istarkov** [comment]
I think your config modules loaders is not defined.

https://github.com/istarkov/babel-plugin-webpack-loaders/blob/ebec1c38e9a65c6eaeacb5e4365237a53b94b668/src/plugin.js#L247

**Comment by giacomorebonato** [comment]
Thank you. That was the problem, now I am facing this, but it is probably an Ava issue.

```
ModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' /public/test/.webpack.res.1462017330691_385514.js in /client/front
```

**Comment by cj** [comment]
@giacomorebonato I'm running into the same issue, did you solve it?  Was it an Ava issue?
