### ISSUE TITLE
bundling multiple css files

### ISSUE THREAD

**Issue by NogsMPLS** [istarkov/babel-plugin-webpack-loaders#8]
I have a css-modules project/library and I'm trying to get all the css exported into 1 css file using this plugin and ExtractTextPlugin()
```javascript
plugins: [ new ExtractTextPlugin('main.css') ]
```
However, what ends up happening, is instead of the multiple CSS files getting inserted into main.css, instead each css file just overwrites the next one.

**Comment by istarkov** [comment]
Yes it works as it must, babel is not a bundler, and this is a webpack plugin for babel ;-) 
So all css are generated in different files, and if file name is the same - the last wins ;-)
You can combine different css as some postprocessing step. In bash its just `cat *.css > bundle.css` command :-)

**Comment by istarkov** [comment]
In realty the problem is as you have saw, webpack to make it synchronous runned every time in new process, so it is impossible to webpack to create bundles.

**Comment by NogsMPLS** [comment]
ya, after i posted this, that's kind of the solution i ended up using. just wanted to confirm it with you. i'll close this now.
