### ISSUE TITLE
How to get rid of the warning "js and jsx files in loaders is unsupported by webpack-loader plugin."

### ISSUE THREAD

**Issue by MoOx** [istarkov/babel-plugin-webpack-loaders#87]
When running tests using AVA, I get a ton of 

```
babel-plugin-webpack-loader:
js and jsx files in loaders is unsupported by webpack-loader plugin.
all babel settings in loader will be skipped
```

It make sense to warn once, but multiple times is maybe too much. Maybe that's related to the fact that AVA use multiple processes? Maybe we can add a flag to disable this warning?

**Comment by istarkov** [comment]
Yes, the problem is multiple processes. Looks like we could disable this warning at all, as it does not solve any issues.
