### ISSUE TITLE
Weird ReferenceError when using a custom webpack loader

### ISSUE THREAD

**Issue by mik01aj** [istarkov/babel-plugin-webpack-loaders#98]
Hi, I'm trying to use your plugin with [this custom webpack loader](https://github.com/sapegin/react-styleguidist/blob/master/loaders/examples.loader.js). The loader produces code that looks roughly like this:

```
var requireMap = {

};
function requireInRuntime(path) {
	if (!requireMap.hasOwnProperty(path)) {
		throw new Error("require() statements can be added only by editing a Markdown example file.")
	}
	return requireMap[path];
}
module.exports = [
  {
    "type": "code",
    "content": "<div><Button>default</Button></div>",
    "evalInContext": function(code, setState) {   var require = requireInRuntime;   return eval(code);}
  },
  // ...
];
```

When I `require` stuff using this loader, it loads fine, but then, when I call the `evalInContext` function it fails with: 

```
     ReferenceError: requireInRuntime is not defined
      at Object.evalInContext (mochatest.js:13:9)
      at Context.<anonymous> (mochatest.js:20:30)
```

This is kinda weird because `requireInRuntime` is defined in the same file, in the file scope. 

**I couldn't believe this error and copied the loader output to an `examples.js` file but then it works fine.**

**Comment by istarkov** [comment]
At the beginning of README.md
`It just replaces require - import statements with webpack loaders results`. 

How could your code example be written 

```
var a = var requireMap = {

};
```

Be sure this plugin does not support any loaders with dynamic code generation.

**Comment by mik01aj** [comment]
whoa.... maybe you could at least wrap the loaded code in IIFE to prevent scope pollution?

**Comment by mik01aj** [comment]
Btw, I was able to work around this bug by doing IIFE myself:

```
    var markdownContent = (function () {
        return require('./ui/Button/examples.md');
    })();
```

But I really really recommend that you do it in the plugin.

**Comment by istarkov** [comment]
For now this plugin solves all my needs, 
if you want it to work with other loaders than described in README, 
please create a PR and tests ;-)

**Comment by loklaan** [comment]
Closing because on inactivity. If @mik01aj would like to still make a PR, then this issue is still here for reference. :smiley:
